action_id: trunk-cache-prune
date: 2023-05-03 01:39:36
run: trunk cache prune --allow-daemon-start=false
run_from: ""
trigger: schedule 24h
result:
  exit_code: 127
  out: ""
  err: "trunk-cache-prune: trunk: command not found\n"
timestamp: 1683077976
full_timestamp:
  nanos: 284169000
  seconds: 1683077976
trunk_version: 1.7.0
